In [1]:
import numpy as np
input_data=np.arange(16)
input_data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [2]:
## tf.data.Dataset.from_tensor_slices

In [3]:
import tensorflow as tf 
dataset=tf.data.Dataset.from_tensor_slices(input_data)
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [5]:
## repeat

In [6]:
dataset=tf.data.Dataset.from_tensor_slices(input_data)
dataset=dataset.repeat(2)
for data in dataset:
    print(data)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [7]:
## batch

In [8]:
dataset=tf.data.Dataset.from_tensor_slices(input_data)
dataset=dataset.repeat(2)
dataset=dataset.batch(4)
for data in dataset:
    print(data)

tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)
tf.Tensor([0 1], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)
tf.Tensor([4 5], shape=(2,), dtype=int32)
tf.Tensor([6 7], shape=(2,), dtype=int32)


In [9]:
## shuffle

In [10]:
dataset=tf.data.Dataset.from_tensor_slices(input_data)
dataset=dataset.shuffle(buffer_size=10)
dataset=dataset.batch(4)
for data in dataset:
    print(data)

tf.Tensor([0 7 5 1], shape=(4,), dtype=int32)
tf.Tensor([3 6 2 4], shape=(4,), dtype=int32)
